#!/usr/bin/env bun

import { formatConv } from './format.js'
import { rl } from './io.js'
import { answer_chain } from './commandr.js'
import { handle_non_interactive } from './nonInteractive'

const Green_RESPONSE_COLOR = '\x1b[32m%s\x1b[0m' // Green
const Blue_RESPONSE_COLOR = '\x1b[94m%s\x1b[0m' // Light Blue

function end() {
  rl.close()
  console.log('\n', Blue_RESPONSE_COLOR, 'Goodbye!')
  process.exit(0)
}

if (process.argv.length > 2) {
  let question = process.argv.slice(2).join(' ')

  let ans = await handle_non_interactive(question)
  console.log(Blue_RESPONSE_COLOR, ans)
  end()
}

/**
 * Runs the chat CLI application to test the bot response.
 *
 * @returns {Promise<void>} A promise that resolves when the chat CLI application is finished.
 */
async function run() {
  const history = []

  /**
   * Asks a question to the user and processes the response.
   */
  async function ask() {
    rl.question('You: ', async (msg) => {
      if (msg.toLocaleLowerCase() === 'exit') {
        end()
      } else {
        try {
          const response = await answer_chain.invoke({
            question: msg,
            history: formatConv(history)
          })
          history.push(msg)
          history.push(response)
          console.log(Blue_RESPONSE_COLOR, response)
        } catch (error) {
          console.error('Error:', error.message)
        }
        ask() // Call ask() again to wait for the next question
      }
    })
  }

  // Start the asking loop
  ask()
}

// Register signal handlers
rl.on('SIGINT', end)
rl.on('SIGTERM', end)

// Run the application
run()
