#!/bin/bash

# Define color variables
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if the bro script exists
if [ ! -f bro ]; then
    echo -e "${RED}The bro script does not exist in the current directory. Please check the path.${NC}"
    exit 1
fi

# Set the executable permission for the bro script
chmod +x bro
echo -e "${GREEN}The script is now executable ✅${NC}"

echo -e "${GREEN}Installing dependencies via bun${NC}"
bun install
echo -e "${GREEN}installed ✅${NC}"

# Create a symbolic link to the bro script in the /usr/local/bin directory
if sudo ln -sf "$(pwd)/bro" /usr/local/bin/; then
    echo -e "${GREEN}Moved the exec file to the system's path ✅${NC}"
else
    echo -e "${RED}Failed to move the exec file to the system's path. Please check your permissions.${NC}"
    # exit 1
fi
# Check if an argument was passed and set it as an environment variable in the .bashrc file
if [ $# -eq 1 ]; then
    echo -e "${GREEN}The argument you passed will be set as an env var with the name COHERE_API_KEY in the file .bashrc${NC}"

    # Update the .bashrc file
    if grep -q "export COHERE_API_KEY" ~/.bashrc; then
        # Update the existing value
        sed -i "s/export COHERE_API_KEY=.*/export COHERE_API_KEY=\"$1\"/" ~/.bashrc
    else
        # Add the new value
        echo "export COHERE_API_KEY=\"$1\"" >> ~/.bashrc
    fi
else
    echo -e "${YELLOW}You didn't provide a COHERE_API_KEY. Make sure you set it manually in the .bashrc file, otherwise you can't use bro.${NC}"
fi
