#!/bin/bash

# Define color variables
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Ensure the script is run with sudo
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Please run as root or use sudo.${NC}"
    exit 1
fi

# Check the user's default shell
user_shell=$SHELL
exec_link_path="/usr/local/bin"

# Print the detected shell
echo -e "${GREEN}Detected shell: $user_shell${NC}"

if [[ $user_shell == */bash ]]; then
    dotFile="$HOME/.bashrc"
elif [[ $user_shell == */zsh ]]; then
    dotFile="$HOME/.zshrc"
else
    echo -e "${RED}Unsupported shell: $user_shell${NC}"
    exit 1
fi

# Check if the bro script exists
if [ ! -f bro ]; then
    echo -e "${RED}The bro script does not exist in the current directory. Please check the path.${NC}"
    exit 1
fi

# Set the executable permission for the bro script
chmod +x bro
echo -e "${GREEN}The script is now executable ✅${NC}"

# Check if bun is installed
if ! command -v bun &> /dev/null; then
    echo -e "${RED}bun is not installed. Please install bun first.${NC}"
    exit 1
fi

echo -e "${GREEN}Installing dependencies via bun${NC}"
if bun install; then
    echo -e "${GREEN}Dependencies installed ✅${NC}"
else
    echo -e "${RED}Failed to install dependencies via bun.${NC}"
    exit 1
fi

# Create a symbolic link to the bro script in the exec_link_path directory
if ln -sf "$(pwd)/bro" $exec_link_path; then
    echo -e "${GREEN}Moved the exec file to the system's path ✅${NC}"
else
    echo -e "${RED}Failed to move the exec file to the system's path. Please check your permissions.${NC}"
    exit 1
fi

# Check if an argument was passed and set it as an environment variable in the dotFile
if [ $# -eq 1 ]; then
    echo -e "${GREEN}The argument you passed will be set as an env var with the name COHERE_API_KEY in the file $dotFile${NC}"

    # Update the dotFile
    if grep -q "export COHERE_API_KEY" "$dotFile"; then
        # Update the existing value
        sed -i "s/export COHERE_API_KEY=.*/export COHERE_API_KEY=\"$1\"/" "$dotFile"
        source "$dotFile"
    else
        # Add the new value
        echo "export COHERE_API_KEY=\"$1\"" >> "$dotFile"
        source $dotFile
    fi
else
    echo -e "${YELLOW}You didn't provide a COHERE_API_KEY. Make sure you set it manually in the $dotFile file, otherwise you can't use bro.${NC}"
fi
