#!/usr/bin/env bash

# Define color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Remove the symbolic link to the bro script from the /usr/local/bin directory
if [ -L "/usr/local/bin/bro" ]; then
    if sudo -E rm "/usr/local/bin/bro"; then
        echo -e "${GREEN}bro has been successfully removed from the system's path ✅${NC}"
    else
        echo -e "${RED}Failed to remove bro from the system's path.${NC}"
    fi
else
    echo -e "${RED}bro is not installed in the system's path.${NC}"
fi


# if grep -q "COHERE_API_KEY" /etc/environment; then
#     sudo sed -i '/COHERE_API_KEY/d' /etc/environment
#     echo -e "${GREEN}COHERE_API_KEY has been successfully removed from /etc/environment ✅${NC}"
# else
#     echo -e "${RED}COHERE_API_KEY is not set in /etc/environment.${NC}"
# fi

# Optional: Remove the node_modules folder
if [ -d "node_modules" ]; then
    rm -rf "node_modules"
    echo -e "${GREEN}node_modules folder has been successfully removed ✅${NC}"
else
    echo -e "${RED}node_modules folder does not exist.${NC}"
fi

# Optional: Remove COHERE_API_KEY environment variable setting
# This might have been added to a profile file like ~/.bashrc or ~/.zshrc
# You need to manually remove it from there if needed
