#!/usr/bin/env bash

# Define color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Remove the symbolic link to the bro script from the /usr/local/bin directory
if [ -L "/usr/local/bin/bro" ]; then
    if sudo -E rm "/usr/local/bin/bro"; then
        echo -e "${GREEN}bro has been successfully removed from the system's path ✅${NC}"
    else
        echo -e "${RED}Failed to remove bro from the system's path.${NC}"
    fi
else
    echo -e "${RED}bro is not installed in the system's path.${NC}"
fi

# Remove the COHERE_API_KEY from the .bashrc file
if grep -q "export COHERE_API_KEY" ~/.bashrc; then
    sed -i "/export COHERE_API_KEY/d" ~/.bashrc
    echo -e "${GREEN}COHERE_API_KEY has been removed from .bashrc ✅${NC}"
else
    echo -e "${YELLOW}COHERE_API_KEY is not set in .bashrc.${NC}"
fi

# Optional: Remove the node_modules folder
if [ -d "node_modules" ]; then
    rm -rf node_modules
    echo -e "${GREEN}node_modules folder has been removed ✅${NC}"
else
    echo -e "${RED}node_modules folder does not exist.${NC}"
fi

# Optional: Remove the bun.lockb file
if [ -f "bun.lockb" ]; then
    rm bun.lockb
    echo -e "${GREEN}bun.lockb file has been removed ✅${NC}"
else
    echo -e "${RED}bun.lockb file does not exist.${NC}"
fi