#!/usr/bin/env bash

# This script updates the local repository and runs the 'bun update' command.

# Exit immediately if a command exits with a non-zero status.
set -e

# Pull the latest changes from the 'main' branch of the remote repository.
echo "Pulling latest changes from the 'main' branch..."
git pull origin main
echo "Pull is done"

# Run the 'bun update' command to update the dependencies.
echo "Updating dependencies with 'bun update'..."
bun update
echo "Update is finished"