#! /usr/bin/env bash

# This script updates the local repository and runs the 'bun update' command.

# Pull the latest changes from the 'main' branch of the remote repository.
git pull

echo "Pull is done"

# Run the 'bun update' command to update the dependencies.
bun update

echo "Update is finished"